#!/bin/sh

source "$ZDOTDIR/zsh-functions"
zsh_add_file "zsh-exports"
zsh_add_file "zsh-aliases"

case $(tty) in
    /dev/tty1)
    clear
    
    eval `dircolors ~/.dircolors`


    if [ -f /home/Piriyan/.local/bin/fbpad ]
    then
			exec  /home/Piriyan/.local/bin/fbpad
    fi
    ;;

    /dev/pts/*)
        if [ -z "${DISPLAY}" ]
        then
						export NCURSES_NO_UTF8_ACS=1
						export TERM='fbpad-256';
        fi
    ;;
    /dev/tty2)
        exec /usr/bin/sway
    ;;
    *)
esac

# some useful options (man zshoptions)
setopt extendedglob nomatch menucomplete
setopt interactive_comments
stty stop undef		# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')


zsh_add_file "zsh-prompt"
# beeping is annoying
unsetopt BEEP

# source $ZDOTDIR/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
# completions
autoload -Uz compinit
zstyle ':completion:*' menu select
zstyle ':completion::complete:lsof:*' menu yes select
zmodload zsh/complist
compinit

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors
autoload -Uz colors && colors

# Useful Functions

# Normal files to source
zsh_add_file "zsh-vim-mode"

zsh_add_file "zoxide-zsh"
zsh_add_file "fzf-zsh"
# source "$ZDOTDIR/fzf-git"

# Plugins
# zsh_add_plugin "zsh-users/zsh-completions"
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "Aloxaf/fzf-tab"
# zsh_add_completion "marlonrichert/zsh-autocomplete"

# Key-bindings
bindkey -s '^o' 'lf-pick | xargs hx\n'
bindkey -s '^s' 'ncdu\n'
bindkey -s '^[d' 'hx "$(zoxide query --interactive)"\n'
bindkey -s '^z' 'zi\n'
bindkey -s '^x' 'ls\n'
bindkey -s '^[^g' 'cd ..\n'
bindkey -s '^[v' '$(cat ~/.clipboard > $(tty))'
bindkey -s '^[c' 'doas !!\n'
bindkey -s '^[ ' ' | l\n'
bindkey -s '^[a' ' "$(zoxide query --interactive)"\n'
bindkey -s '^[r' 'cd -\n'
bindkey -s '^[s' ' **\t'
bindkey -s '^v' 'cd **\t'
bindkey -s '^[t' 'fzf --bind "enter:execute( {})"^[[D^[[D^[[D^[[D^[[D'
bindkey -s '^[k' 'kill **^I'

bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# FZF
# source /usr/share/fzf/key-bindings.zsh
# source /usr/share/fzf/completion.zsh
# source $ZDOTDIR/zoxide-zsh
# source $ZDOTDIR/fzf-zsh

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line


zstyle ':completion:*:git-checkout:*' sort flash
zstyle ':completion:*:descriptions:*' format '[%d]'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color=always $realpath'
zstyle ':fzf-tab:*' switch-group ',' '.'
