#!/bin/sh

# [ -f /tmp/dbus-session-addr ] && echo try >> /home/Piriyan/piptry || exit 1
# sv start /home/Piriyan/.service/dbus-sess || exit 1

# cat /tmp/dbus-session-addr > /home/Piriyan/pipdbus-addr

exec env XDG_RUNTIME_DIR=/run/user/1000 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus /usr/bin/pipewire
# exec env XDG_RUNTIME_DIR=/run/user/1000 DBUS_SESSION_BUS_ADDRESS=$(cat /tmp/dbus-session-addr) /usr/bin/pipewire 2>/home/Piriyan/piplog 1>&2
